### ISSUE TITLE
执行git apply --3way后没有生成aspectd.dart文件

### ISSUE THREAD

**Issue by kasentom** [LianjiaTech/Beike_AspectD#1]
下载了demo工程后按照readme.md配置后，把demo跑起来，解析发现dill文件里面并没有add的插桩代码。检查发现在执行这部git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch 的时候，并没有在flutter sdk的packages/flutter_tools/lib/src中生成aspectd.dart文件。

和我这里的操作有关么？

版本配置:
Flutter 2.5.3
Dart 2.14.4

我最开始是执行这个，有提示这个错误
`
cd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools 
git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch 

error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index
error: packages/flutter_tools/lib/src/build_system/targets/web.dart: does not match index
error: packages/flutter_tools/lib/src/commands/build_bundle.dart: does not match index
error: packages/flutter_tools/lib/src/compile.dart: does not match index
error: packages/flutter_tools/lib/src/web/chrome.dart: does not match index
`

我在这个目录执行这命令是没有错误，但是aspectd.dart没有生成
`
pwd
/Users/xxxx/tools/aspected/flutter/packages/flutter_tools/bin
git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch 
`

**Comment by soloxiao** [comment]
> 下载了demo工程后按照readme.md配置后，把demo跑起来，解析发现dill文件里面并没有add的插桩代码。检查发现在执行这部git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch 的时候，并没有在flutter sdk的packages/flutter_tools/lib/src中生成aspectd.dart文件。
> 
> 和我这里的操作有关么？
> 
> 版本配置: Flutter 2.5.3 Dart 2.14.4
> 
> 我最开始是执行这个，有提示这个错误 ` cd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch
> 
> error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index error: packages/flutter_tools/lib/src/build_system/targets/web.dart: does not match index error: packages/flutter_tools/lib/src/commands/build_bundle.dart: does not match index error: packages/flutter_tools/lib/src/compile.dart: does not match index error: packages/flutter_tools/lib/src/web/chrome.dart: does not match index `
> 
> 我在这个目录执行这命令是没有错误，但是aspectd.dart没有生成 `pwd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools/bin git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch`


是 /Users/xxxx/tools/aspected/flutter/packages/flutter_tools
而不是/Users/xxxx/tools/aspected/flutter/packages/flutter_tools/bin

**Comment by kasentom** [comment]
> > 下载了demo工程后按照readme.md配置后，把demo跑起来，解析发现dill文件里面并没有add的插桩代码。检查发现在执行这部git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch 的时候，并没有在flutter sdk的packages/flutter_tools/lib/src中生成aspectd.dart文件。
> > 和我这里的操作有关么？
> > 版本配置: Flutter 2.5.3 Dart 2.14.4
> > 我最开始是执行这个，有提示这个错误 ` cd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch
> > error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index error: packages/flutter_tools/lib/src/build_system/targets/web.dart: does not match index error: packages/flutter_tools/lib/src/commands/build_bundle.dart: does not match index error: packages/flutter_tools/lib/src/compile.dart: does not match index error: packages/flutter_tools/lib/src/web/chrome.dart: does not match index `
> > 我在这个目录执行这命令是没有错误，但是aspectd.dart没有生成 `pwd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools/bin git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch`
> 
> 是 /Users/xxxx/tools/aspected/flutter/packages/flutter_tools 而不是/Users/xxxx/tools/aspected/flutter/packages/flutter_tools/bin

这边重新执行还是有存在这个问题。正常情况下是会有对应的aspectd.dart文件生成么
`
cd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools 

git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch 
error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index
error: packages/flutter_tools/lib/src/build_system/targets/web.dart: does not match index
error: packages/flutter_tools/lib/src/commands/build_bundle.dart: does not match index
error: packages/flutter_tools/lib/src/compile.dart: does not match index
error: packages/flutter_tools/lib/src/web/chrome.dart: does not match index
`

**Comment by kasentom** [comment]
> > 下载了demo工程后按照readme.md配置后，把demo跑起来，解析发现dill文件里面并没有add的插桩代码。检查发现在执行这部git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch 的时候，并没有在flutter sdk的packages/flutter_tools/lib/src中生成aspectd.dart文件。
> > 和我这里的操作有关么？
> > 版本配置: Flutter 2.5.3 Dart 2.14.4
> > 我最开始是执行这个，有提示这个错误 ` cd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch
> > error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index error: packages/flutter_tools/lib/src/build_system/targets/web.dart: does not match index error: packages/flutter_tools/lib/src/commands/build_bundle.dart: does not match index error: packages/flutter_tools/lib/src/compile.dart: does not match index error: packages/flutter_tools/lib/src/web/chrome.dart: does not match index `
> > 我在这个目录执行这命令是没有错误，但是aspectd.dart没有生成 `pwd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools/bin git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch`
> 
> 是 /Users/xxxx/tools/aspected/flutter/packages/flutter_tools 而不是/Users/xxxx/tools/aspected/flutter/packages/flutter_tools/bin

找到原因了，原来是我最开始的时候在错误的路径执行git apply操作出现失败。这时候已经产生了脏文件。后续需要把当前flutter的代码重置或者重新拉一份才可以。

**Comment by soloxiao** [comment]
> > > 下载了demo工程后按照readme.md配置后，把demo跑起来，解析发现dill文件里面并没有add的插桩代码。检查发现在执行这部git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch 的时候，并没有在flutter sdk的packages/flutter_tools/lib/src中生成aspectd.dart文件。
> > > 和我这里的操作有关么？
> > > 版本配置: Flutter 2.5.3 Dart 2.14.4
> > > 我最开始是执行这个，有提示这个错误 `cd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index error: packages/flutter_tools/lib/src/build_system/targets/web.dart: does not match index error: packages/flutter_tools/lib/src/commands/build_bundle.dart: does not match index error: packages/flutter_tools/lib/src/compile.dart: does not match index error: packages/flutter_tools/lib/src/web/chrome.dart: does not match index`
> > > 我在这个目录执行这命令是没有错误，但是aspectd.dart没有生成 `pwd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools/bin git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch`
> > 
> > 
> > 是 /Users/xxxx/tools/aspected/flutter/packages/flutter_tools 而不是/Users/xxxx/tools/aspected/flutter/packages/flutter_tools/bin
> 
> 这边重新执行还是有存在这个问题。正常情况下是会有对应的aspectd.dart文件生成么 ` cd /Users/xxxx/tools/aspected/flutter/packages/flutter_tools
> 
> git apply --3way /Users/xxxx/tools/aspected/Beike_AspectD/inner/flutter_tools.patch error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index error: packages/flutter_tools/lib/src/build_system/targets/web.dart: does not match index error: packages/flutter_tools/lib/src/commands/build_bundle.dart: does not match index error: packages/flutter_tools/lib/src/compile.dart: does not match index error: packages/flutter_tools/lib/src/web/chrome.dart: does not match index `

是的。建议尝试stash之后重新apply

<img width="1249" alt="截屏2021-12-28 下午2 10 29" src="https://user-images.githubusercontent.com/7533092/147533973-3ea0784a-7041-4e94-b8df-fa362f5be14c.png">
