### ISSUE TITLE
Hook构造方法报错

### ISSUE THREAD

**Issue by Night1992** [LianjiaTech/Beike_AspectD#10]
工程里example，hook构造方法的时候，报错提示：type 'Constructor' is not a subtype of type 'Procedure'

**Comment by soloxiao** [comment]
> 工程里example，hook构造方法的时候，报错提示：type 'Constructor' is not a subtype of type 'Procedure'

具体在哪一个分支呢？

**Comment by Night1992** [comment]
3.0.0分支，实例代码：hook_example.dart里的，Call demo里的，可能有些demo方法我自己做过一点点改动，但是基本没变，具体方法：

//构造方法
@Call("package:example/receiver_test.dart", "Receiver", "+Receiver")
@pragma("vm:entry-point")
dynamic receiveTapped2(PointCut pointcut) {
  dynamic obj = pointcut.proceed();
  print('[beike_aspectd]: call constructor method!');
  pointcut.proceed();
  return obj;
}

**Comment by soloxiao** [comment]
> 3.0.0分支，实例代码：hook_example.dart里的，Call demo里的，可能有些demo方法我自己做过一点点改动，但是基本没变，具体方法：
> 
> //构造方法 @call("package:example/receiver_test.dart", "Receiver", "+Receiver") @pragma("vm:entry-point") dynamic receiveTapped2(PointCut pointcut) { dynamic obj = pointcut.proceed(); print('[beike_aspectd]: call constructor method!'); pointcut.proceed(); return obj; }

我这里没有复现你这个问题。不过demo里确实有问题，下面这个方法应该是static的。麻烦拉取最新代码尝试是否还有问题

> @Call("package:example/receiver_test.dart", "Receiver", "+Receiver")
> @pragma("vm:entry-point")
> static dynamic receiveTapped(PointCut pointcut) {
>   dynamic obj = pointcut.proceed();
>   print('[beike_aspectd]: call constructor method!');
>   pointcut.proceed();
>   return obj;
> }
