### ISSUE TITLE
静态方法用execute报错

### ISSUE THREAD

**Issue by Night1992** [LianjiaTech/Beike_AspectD#11]
3.0.0分支，hook静态方法，比如demo里的

`@Execute("package:example/receiver_test.dart", "Receiver", "+tap")
@pragma("vm:entry-point")
static dynamic tap(PointCut pointcut) {
  print('[beike_aspectd]: Execute static method!');
  pointcut.proceed();
}`

报错：

Unhandled exception:
[        ]            Crash when compiling null,
[        ]            at character offset null:
[        ]            NoSuchMethodError: The getter 'nonNullable' was called on null.
[        ]            Receiver: null
[        ]            Tried calling: nonNullable
[        ]            #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
[        ]            #1      Procedure.getterType (package:kernel/ast.dart:3204:59)
[        ]            #2      AopUtils.insertProceedBranch

**Comment by soloxiao** [comment]
已经在3.0.0版本分支中修复，请拉取代码后尝试是否还有此问题
