### ISSUE TITLE
如何hook一个带泛型的方法

### ISSUE THREAD

**Issue by ChunSongChen** [LianjiaTech/Beike_AspectD#12]
hook 带泛型方法时报错Invalid argument(s): Type parameter TypeParameter(T) is not indexed

**Comment by soloxiao** [comment]
使用的execute方式吗？execute目前支持不了泛型的hook

**Comment by ChunSongChen** [comment]
感谢,目前又碰到了新的问题,null-safety/2.5.3分支执行generate_plugins_entry.dart文件会报错,目前有自定义transform的相关文档吗

**Comment by soloxiao** [comment]
> 感谢,目前又碰到了新的问题,null-safety/2.5.3分支执行generate_plugins_entry.dart文件会报错,目前有自定义transform的相关文档吗

自定义transfrom是指什么？
