### ISSUE TITLE
flutter2.10.5使用2.10.4分支出现null safety

### ISSUE THREAD

**Issue by softAlexs** [LianjiaTech/Beike_AspectD#13]
: Error: A library can't opt out of null safety by default, when using sound null safety.
../…/lib/aspectd.dart:1
    // @dart=2.8
    ^^^^^^^^^^^^
: Error: A library can't opt out of null safety by default, when using sound null safety.
../…/aop/aop.dart:1
    // @dart=2.8
    ^^^^^^^^^^^^
: Error: A library can't opt out of null safety by default, when using sound null safety.
../…/annotation/call.dart:1
    // @dart=2.8
    ^^^^^^^^^^^^
: Error: A library can't opt out of null safety by default, when using sound null safety.
../…/annotation/execute.dart:1
    // @dart=2.8
    ^^^^^^^^^^^^
: Error: A library can't opt out of null safety by default, when using sound null safety.
../…/annotation/inject.dart:1
    // @dart=2.8
    ^^^^^^^^^^^^
: Error: A library can't opt out of null safety by default, when using sound null safety.
../…/annotation/pointcut.dart:1
    // @dart=2.8
    ^^^^^^^^^^^^
: Error: A library can't opt out of null safety by default, when using sound null safety.
../…/beike_annotation/add.dart:1
    // @dart=2.8
    ^^^^^^^^^^^^
: Error: A library can't opt out of null safety by default, when using sound null safety.
../…/beike_annotation/field_get.dart:1
    // @dart=2.8
    ^^^^^^^^^^^^
: Error: A library can't opt out of null safety by default, when using sound null safety.
../…/annotation/annotation_info.dart:1
    // @dart=2.8
    ^^^^^^^^^^^^
    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:
     - package:beike_aspectd
    For solutions, see https://dart.dev/go/unsound-null-safety
    Failed to package /Users/xx/Desktop/xx/xxxx.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning

**Comment by monkeyxdd** [comment]
同样的问题

**Comment by soloxiao** [comment]
已在[null-safety/2.10.4](https://github.com/LianjiaTech/Beike_AspectD/tree/null-safety/2.10.4)分支适配
