### ISSUE TITLE
运行项目后修改代码再次运行出现Unhandled exception，需要执行flutter clean清理缓存才可以恢复

### ISSUE THREAD

**Issue by softAlexs** [LianjiaTech/Beike_AspectD#14]
<img width="1181" alt="WX20220802-195451@2x" src="https://user-images.githubusercontent.com/15091679/182368614-bc4deff0-e2c2-4d75-82b5-593443f94a3d.png">
Unhandled exception:
root::package:beike_aspectd/src/plugins/aop/annotation/pointcut.dart::PointCut::@methods::aop_stub_0 is already bound to Reference to package:beike_aspectd/src/plugins/aop/annotation/pointcut.dart::PointCut::@methods::aop_stub_0 with node PointCut.aop_stub_0 (Procedure:114447), trying to bind to Reference to PointCut.aop_stub_0 with node PointCut.aop_stub_0 (Procedure:4371882)
package:beike_aspectd/…/annotation/pointcut.dart:1
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:236:7)
#1      Class.computeCanonicalNames (package:kernel/ast.dart:1284:51)
#2      Library.computeCanonicalNames (package:kernel/ast.dart:509:14)
#3      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:13669:13)
#4      Component.computeCanonicalNames (package:kernel/ast.dart:13631:7)
#5      sortComponent (package:vm/kernel_front_end.dart:702:13)
#6      FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:696:5)
#7      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:576:13)
<asynchronous suspension>
#8      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1154:11)
<asynchronous suspension>

2
the Dart compiler exited unexpectedly.

**Comment by soloxiao** [comment]
> <img alt="WX20220802-195451@2x" width="1181" src="https://user-images.githubusercontent.com/15091679/182368614-bc4deff0-e2c2-4d75-82b5-593443f94a3d.png">
> 
> Unhandled exception: root:📦beike_aspectd/src/plugins/aop/annotation/pointcut.dart::PointCut::@methods::aop_stub_0 is already bound to Reference to package:beike_aspectd/src/plugins/aop/annotation/pointcut.dart::PointCut::@methods::aop_stub_0 with node PointCut.aop_stub_0 (Procedure:114447), trying to bind to Reference to PointCut.aop_stub_0 with node PointCut.aop_stub_0 (Procedure:4371882) package:beike_aspectd/…/annotation/pointcut.dart:1 #0 CanonicalName.bindTo (package:kernel/canonical_name.dart:236:7) #1 Class.computeCanonicalNames (package:kernel/ast.dart:1284:51) #2 Library.computeCanonicalNames (package:kernel/ast.dart:509:14) #3 Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:13669:13) #4 Component.computeCanonicalNames (package:kernel/ast.dart:13631:7) #5 sortComponent (package:vm/kernel_front_end.dart:702:13) #6 FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:696:5) #7 FrontendCompiler.compile (package:frontend_server/frontend_server.dart:576:13) #8 listenAndCompile. (package:frontend_server/frontend_server.dart:1154:11)
> 2 the Dart compiler exited unexpectedly.

请问使用的是哪个版本呢？
