### ISSUE TITLE
3.0.5分支下混合开发模式安卓，debug模式正常，release模式触发点击事件后报错

### ISSUE THREAD

**Issue by weicheng59** [LianjiaTech/Beike_AspectD#17]
` I/flutter: type '_OneByteString' is not a subtype of type 'int' of 'index'
I/flutter: #0      PointCut.aop_stub_26 (package:beike_aspectd/src/plugins/aop/annotation/pointcut.dart)
I/flutter: #1      PointCut.proceed (package:beike_aspectd/src/plugins/aop/annotation/pointcut.dart)
I/flutter: #2      ClickAopHook.hookInvokeCallback (package:tdx_flutter/aop/hook_entry_points.dart:36)
I/flutter: #3      new _GrowableList._literal2 (dart:core-patch/growable_array.dart)
I/flutter: #4      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart)
I/flutter: #5      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:276)`

Flutter版本，3.0.5
混合开发模式是否需要自己编译引擎？

**Comment by soloxiao** [comment]
beike_aspectd不需要定制引擎，可以通过下面方法把dill解析出来来排查PointCut.aop_stub_26方法的具体实现

First you need to download the dart-sdk and checkout to the corresponding revision of flutter. The revision of dart can be found at path_to_flutter/bin/cache/dart-sdk/revision.
Run the following command.
path_to_flutter/bin/cache/dart-sdk/bin/dart  path_to_dart/pkg/vm/bin/dump_kernel.dart path_to_your_project/.dart_tool/flutter_build/***/app.dill output_path/out.dill.txt
Open output_path/out.dill.txt file, check if your code is hook.

**Comment by weicheng59** [comment]
https://github.com/weicheng59/beike_aop_demo

最基础复现的demo，flutter默认的工程

**Comment by weicheng59** [comment]
3.0.5分支上测试已解决，并可以在excute里使用泛型
