### ISSUE TITLE
有办法hook住所有的方法吗？

### ISSUE THREAD

**Issue by LDouble** [LianjiaTech/Beike_AspectD#2]
我们现在想hook住所有的方法，然后拿到执行某些操作后，具体执行的代码包含了哪个类、哪个方法

**Comment by soloxiao** [comment]
> 我们现在想hook住所有的方法，然后拿到执行某些操作后，具体执行的代码包含了哪个类、哪个方法

执行某些操作是指执行某一个方法吗？比如点击某个按钮？类和方法以什么形式返回呢？目前没有这个功能

**Comment by LDouble** [comment]
@Call("package:.*", ".*",
    "-.*", isRegex: true)
@pragma("vm:entry-point")
void _incrementCounter4(PointCut pointcut) {
  print('[beike_aspectd]: call instance method2!');
  pointcut.proceed();
}

我使用上面这个UI则去切面，会报下面的从无。
rash when compiling null,
at character offset null:
Null check operator used on a null value
#0      _WidgetCallSiteTransformer._computeLocation (package:kernel/transformations/track_widget_constructor_locations.dart:257:20)
#1      _WidgetCallSiteTransformer._addLocationArgument (package:kernel/transformations/track_widget_constructor_locations.dart:212:7)
#2      _WidgetCallSiteTransformer.visitConstructorInvocation (package:kernel/transformations/track_widget_constructor_locations.dart:227:5)
#3      ConstructorInvocation.accept (package:kernel/ast.dart:5995:44)
#4      Transformer.transform (package:kernel/visitor.dart:1242:21)
#5      NamedExpression.transformChildren (package:kernel/ast.dart:4835:17)
#6      Transformer.defaultTreeNode (package:kernel/visitor.dart:1299:10)
#7      TreeVisitor.visitNamedExpression (package:kernel/visitor.dart:320:51)

**Comment by LDouble** [comment]
其实就是想通过hook的方式来拿到我浏览整个页面，都执行了哪些函数/哪些类

**Comment by soloxiao** [comment]
> 其实就是想通过hook的方式来拿到我浏览整个页面，都执行了哪些函数/哪些类

不建议全局的通过正则去匹配hook，基于以下几点：
1. 大量修改Flutter框架的代码可能产生不可预知的问题；
2. 大量通过Call方式hook，会修改每一个方法调用并添加相应的方法，会对包大小产生影响；
3. 对执行效率也会造成影响。

建议将需要hook的包限制在更小的范围内，比如只针对业务代码。

**Comment by LDouble** [comment]
thx, 我还遇到一个问题，重新提一个issue，辛苦帮忙确认一下呀
