### ISSUE TITLE
嵌套函数hook会报错---Null check operator used on a null value

### ISSUE THREAD

**Issue by LDouble** [LianjiaTech/Beike_AspectD#3]
```
class TextRightImageModel {
  String showName;

  String rightIcon;

  Widget showCardWidget(BuildContext context) {
    return Container(
      padding: const EdgeInsets.only(left: 4.0, right: 4.0),
      alignment: Alignment.center,
      child: wrapTextLimit(context, const Text("")),
    );
  }

  Widget wrapTextLimit(BuildContext str, Widget widget) {
    return widget;
  }

}
```

我的业务代码是上面这个，然后通过以下代码去hook，编译的时候一定会报错
```
 @Call(
      'package:test/test.dart', 'TextRightImageModel', '-.*',
      isRegex: true)
  @pragma("vm:entry-point")
  dynamic _aop_Two(PointCut pointcut) {
    return pointcut.proceed();
  }
```

flutter 环境:2.5.3

**Comment by LDouble** [comment]
另外在debug包能hook，打profile和release都会报错

**Comment by soloxiao** [comment]
> 另外在debug包能hook的类，打profile和release都会报错

问题已在最新的提交中修复

**Comment by LDouble** [comment]
nice, 不过在打release包的时候还是会提示
Crash when compiling null,
at character offset null:
Null check operator used on a null value
#0      ConstantEvaluator._recordConstructorCoverage

**Comment by LDouble** [comment]
请问前辈这个有什么本地调试的办法吗？
我也想尝试自己修复一下遇到的问题。

**Comment by soloxiao** [comment]
> nice, 不过在打release包的时候还是会提示
> Crash when compiling null,
> at character offset null:
> Null check operator used on a null value
> #0 ConstantEvaluator._recordConstructorCoverage
![截屏2022-01-06 上午10 21 47](https://user-images.githubusercontent.com/7533092/148317995-228aed66-06e4-48d7-a3e6-cefacf4f072b.png)
用的还是之前给的代码吗？我用你之前给的代码在release没有问题的。
可以执行clean之后再次尝试
`flutter clean`

**Comment by soloxiao** [comment]
> 请问前辈这个有什么本地调试的办法吗？
> 我也想尝试自己修复一下遇到的问题。本地现在已经可以自己编译了，但是没办法断点，比较头疼

这个我后面会更新一下原理和调试文档

**Comment by LDouble** [comment]
> > 请问前辈这个有什么本地调试的办法吗？
> > 我也想尝试自己修复一下遇到的问题。本地现在已经可以自己编译了，但是没办法断点，比较头疼
> 
> 这个我后面会更新一下原理和调试文档

我在插桩实际业务的时候，还是有一些报错，比如说泛型，有些报错我也不知道是什么业务代码引起的，我可能需要等前面更新一下调试文档了，来确定具体的问题，感谢！

**Comment by soloxiao** [comment]
> 

调试文档已更新

https://github.com/LianjiaTech/Beike_AspectD/blob/2.5.3/doc/如何调试.md

**Comment by LDouble** [comment]
3q
