### ISSUE TITLE
为啥除了null-safety的其他分支，跑起来都报错

### ISSUE THREAD

**Issue by tanzhihao1qaz** [LianjiaTech/Beike_AspectD#32]
其他分支的都会报这个问题，A library can't opt out of null safety by default, when using sound null safety

**Comment by tanzhihao1qaz** [comment]
我知道怎么集成使用了，有问题的朋友可以问我

**Comment by zhangshuqi** [comment]
同学 您换一个没有集成Beike_AspectD的项目运行会报错吗

**Comment by tanzhihao1qaz** [comment]
> 同学 您换一个没有集成Beike_AspectD的项目运行会报错吗

你报啥错？我的不会
