### ISSUE TITLE
Flutter3.0.0版本没有生成aspectd.dart文件

### ISSUE THREAD

**Issue by jincan-he** [LianjiaTech/Beike_AspectD#6]
在Flutter3.0环境下执行：
cd ...path/to/flutter/packages/flutter_tools/
git apply --3way path-for-beike_aspectd-package/inner/flutter_tools.patch
rm ../../bin/cache/flutter_tools.stamp
之后没有反应，flutter_tools/bin目录下没有aspectd.dart文件。
执行第二步apply之后本地没有任何代码变化，git status是clean的。
![image](https://user-images.githubusercontent.com/106218422/170188316-e9669c0f-4cea-480f-9621-c16fe1fd72eb.png)

**Comment by soloxiao** [comment]
<img width="1473" alt="截屏2022-05-25 下午2 25 49" src="https://user-images.githubusercontent.com/7533092/170194792-ea3ccbed-793a-46e2-b8f1-ba8996e27fc2.png">
如上图，aspectd.dart会被添加到上面的路径，而不是在flutter_tools/bin目录下。
patch apply后修改的文件如下：
<img width="490" alt="截屏2022-05-25 下午2 30 44" src="https://user-images.githubusercontent.com/7533092/170195391-def97be0-6acb-4dcc-99cb-3dd3fd2cbe61.png">

**Comment by jincan-he** [comment]
> <img alt="截屏2022-05-25 下午2 25 49" width="1473" src="https://user-images.githubusercontent.com/7533092/170194792-ea3ccbed-793a-46e2-b8f1-ba8996e27fc2.png">
> 
> 如上图，aspectd.dart会被添加到上面的路径，而不是在flutter_tools/bin目录下。 patch apply后修改的文件如下：
> <img alt="截屏2022-05-25 下午2 30 44" width="490" src="https://user-images.githubusercontent.com/7533092/170195391-def97be0-6acb-4dcc-99cb-3dd3fd2cbe61.png">

我这边在上述的路径下没有生成对应的文件，并且本地也没有修改记录。怀疑是apply patch失败了，但是没有产生任何报错

**Comment by soloxiao** [comment]
如果git apply不生效的话，可以考虑手动合并，或者使用下面这个gist将相应的文件覆盖即可

<script src="https://gist.github.com/soloxiao/b67750c1447689796f6bad4b14bbb313.js"></script>

**Comment by jincan-he** [comment]
我的同事根据你的patch重新写了文件，然后生成的patch是可用的。

所以应该是patch生成的有问题。我这边是用的Flutter3.0的stable分支，commit为：ee4e09cce01d6f2d7f4baebd247fde02e5008851

请问是否和分支、commit有关？
若是有关，是否可以在介绍文档中进行补充说明切换到对应的git commit

**Comment by soloxiao** [comment]
> 我的同事根据你的patch重新写了文件，然后生成的patch是可用的。
> 
> 所以应该是patch生成的有问题。我这边是用的Flutter3.0的stable分支，commit为：ee4e09cce01d6f2d7f4baebd247fde02e5008851
> 
> 请问是否和分支、commit有关？ 若是有关，是否可以在介绍文档中进行补充说明切换到对应的git commit

https://gist.github.com/soloxiao/9efc4aac89d8db84692af3e798d9b584
麻烦使用上面这个patch试一下呢?

**Comment by jincan-he** [comment]
> 

依旧不行，切换到stable分支之后，apply之后没有文件变更。

**Comment by soloxiao** [comment]
> 依旧不行，切换到stable分支之后，apply之后没有文件变更。

不好意思回复晚了，最近比较忙。

我已经更新了最新的patch，这个patch应该没有问题了。
需要注意的是最新的patch需要在flutter根目录下执行，如下图

![image](https://user-images.githubusercontent.com/7533092/173593150-ea275ffb-9c5f-4a30-8eff-30106ac36972.png)
