### ISSUE TITLE
按着调试文档步骤调试无法生成frontend_server参数

### ISSUE THREAD

**Issue by luckyBoyFeng** [LianjiaTech/Beike_AspectD#8]
按着调试文档调试流程调试，在调试Flutter_tools时获取不到frontend_server参数。想问一下我的配置参数是否错误。  在Dart Command Line App中我的Working directory 选择的是Beike_AspectD/example文件，想问一下是不是这个选择的不对导致的。希望得到解答。
![image](https://user-images.githubusercontent.com/17785672/173554737-b3d66e20-46ba-48cc-a4be-bccc7ad645bb.png)

**Comment by soloxiao** [comment]
> 按着调试文档调试流程调试，在调试Flutter_tools时获取不到frontend_server参数。想问一下我的配置参数是否错误。 在Dart Command Line App中我的Working directory 选择的是Beike_AspectD/example文件，想问一下是不是这个选择的不对导致的。希望得到解答。
> ![image](https://user-images.githubusercontent.com/17785672/173554737-b3d66e20-46ba-48cc-a4be-bccc7ad645bb.png)

![image](https://user-images.githubusercontent.com/7533092/173575010-83e36cb3-4bd4-44ef-b367-006e4ab57333.png)
这一步patch是否成功？

可以尝试在下面这一行打断点来获取参数。

![image](https://user-images.githubusercontent.com/7533092/173575496-7f550dc7-1a37-4d3a-a4f3-f179c91571c6.png)

**Comment by luckyBoyFeng** [comment]
严格按照上述步骤执行到flutter_tools.dart步骤时还是未获取到frontend_server参数，以下是报错日志：
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:54959/C4tzlXkoSoc=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A54959%2FC4tzlXkoSoc%3D%2Fws
lib/main.dart--verbose
[ +105 ms] executing: sysctl hw.optional.arm64
[  +28 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[   +7 ms] executing: [/Users/aa/workspace/flutter/sdk/home/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +46 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] executing: [/Users/aa/workspace/flutter/sdk/home/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[ +111 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[  +10 ms] executing: [/Users/aa/workspace/flutter/sdk/home/] git rev-parse --abbrev-ref --symbolic @{u}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/aa/workspace/flutter/sdk/home/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +141 ms] executing: [/Users/aa/workspace/flutter/sdk/fhome/] git rev-parse --abbrev-ref HEAD
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +5 ms] stable
[  +13 ms] executing: sw_vers -productName
[  +39 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +25 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.6.2
[        ] executing: sw_vers -buildVersion
[  +24 ms] Exit code 0 from: sw_vers -buildVersion
[   +1 ms] 20G314
[  +66 ms] Could not find a command named "lib/main.dart".

[   +4 ms] Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
[  +11 ms] ensureAnalyticsSent: 8ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 64

Process finished with exit code 64

**Comment by luckyBoyFeng** [comment]
在执行 git apply --3way /Users/aa/workspace2/Beike_AspectD/inner/flutter_tools.patch 时发现控制台报错了，以下是报错日志：
error: packages/flutter_tools/lib/src/aop/aop_manager.dart: does not exist in index
error: cannot read the current contents of 'packages/flutter_tools/lib/src/aop/aop_manager.dart'
Falling back to direct application...
error: packages/flutter_tools/lib/src/aop/hook_factory.dart: does not exist in index
error: cannot read the current contents of 'packages/flutter_tools/lib/src/aop/hook_factory.dart'
Falling back to direct application...
error: packages/flutter_tools/lib/src/aspectd.dart: does not exist in index
error: cannot read the current contents of 'packages/flutter_tools/lib/src/aspectd.dart'
Falling back to direct application...
error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index
error: packages/flutter_tools/lib/src/build_system/targets/web.dart: does not match index
error: packages/flutter_tools/lib/src/commands/build_bundle.dart: does not match index
error: packages/flutter_tools/lib/src/compile.dart: does not match index
error: packages/flutter_tools/lib/src/web/chrome.dart: does not match index

我在flutter_tools发现了补丁文件：
![image](https://user-images.githubusercontent.com/17785672/173727040-465f3720-2586-49cd-91bd-93ff2cb4fe73.png)

**Comment by soloxiao** [comment]
> 在执行 git apply --3way /Users/aa/workspace2/Beike_AspectD/inner/flutter_tools.patch 时发现控制台报错了，以下是报错日志： error: packages/flutter_tools/lib/src/aop/aop_manager.dart: does not exist in index error: cannot read the current contents of 'packages/flutter_tools/lib/src/aop/aop_manager.dart' Falling back to direct application... error: packages/flutter_tools/lib/src/aop/hook_factory.dart: does not exist in index error: cannot read the current contents of 'packages/flutter_tools/lib/src/aop/hook_factory.dart' Falling back to direct application... error: packages/flutter_tools/lib/src/aspectd.dart: does not exist in index error: cannot read the current contents of 'packages/flutter_tools/lib/src/aspectd.dart' Falling back to direct application... error: packages/flutter_tools/lib/src/build_system/targets/common.dart: does not match index error: packages/flutter_tools/lib/src/build_system/targets/web.dart: does not match index error: packages/flutter_tools/lib/src/commands/build_bundle.dart: does not match index error: packages/flutter_tools/lib/src/compile.dart: does not match index error: packages/flutter_tools/lib/src/web/chrome.dart: does not match index
> 
> 我在flutter_tools发现了补丁文件： ![image](https://user-images.githubusercontent.com/17785672/173727040-465f3720-2586-49cd-91bd-93ff2cb4fe73.png)

可以用最新的patch文件试试吗？我更新了patch文件。

需要注意的是，patch apply需要从flutter根目录下执行，如下图。

![image](https://user-images.githubusercontent.com/7533092/174078967-b05279ef-7fdd-44fb-9bf8-48516f86c006.png)
